# Generated by Django 5.2.6 on 2026-03-04 10:47

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Tạo slug cho tất cả sản phẩm hiện có"""
    Product = apps.get_model('shop', 'Product')
    
    for product in Product.objects.all():
        if not product.slug:
            # Tạo base slug từ tên
            base_slug = slugify(product.name)
            slug = base_slug
            counter = 1
            
            # Đảm bảo slug unique
            while Product.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            product.slug = slug
            product.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    """Xóa tất cả slugs khi rollback"""
    Product = apps.get_model('shop', 'Product')
    Product.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_avg_rating_product_slug_product_sold_count_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
