# Generated by Django 5.2.6 on 2026-03-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_add_slug_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_group',
            field=models.CharField(choices=[('men', 'Nam'), ('women', 'Nữ'), ('accessories', 'Phụ Kiện'), ('other', 'Khác')], default='other', help_text='Nhóm hiển thị trong mega menu', max_length=20),
        ),
    ]
