# Generated by Django 5.2.6 on 2025-11-18 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cartitem_created_at_cartitem_is_reserved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Phần trăm'), ('fixed', 'Số tiền cố định'), ('free_shipping', 'Miễn phí vận chuyển')], default='percentage', max_length=20)),
                ('occasion_type', models.CharField(choices=[('birthday', 'Sinh nhật'), ('promotion', 'Khuyến mãi'), ('seasonal', 'Theo mùa'), ('first_order', 'Đơn hàng đầu'), ('loyalty', 'Khách hàng thân thiết')], default='promotion', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị giảm')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giảm tối đa (cho phần trăm)')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá trị đơn hàng tối thiểu')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lần sử dụng tối đa')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='Số lần/khách')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Đã sử dụng')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Có hiệu lực từ')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Có hiệu lực đến')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('is_public', models.BooleanField(default=False, verbose_name='Công khai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(verbose_name='Có hiệu lực từ')),
                ('valid_to', models.DateTimeField(verbose_name='Có hiệu lực đến')),
                ('is_used', models.BooleanField(default=False, verbose_name='Đã sử dụng')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian sử dụng')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhận')),
                ('notified', models.BooleanField(default=False, verbose_name='Đã thông báo')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thông báo')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='shop.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to='shop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher của khách',
                'verbose_name_plural': 'Voucher của khách',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'coupon', 'valid_from')},
            },
        ),
    ]
