# Generated by Django 5.2.6 on 2026-01-07 08:34

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_discount_amount_order_used_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá khuyến mãi'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.variant_image_path, verbose_name='Ảnh variant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá bán'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã voucher')),
                ('name', models.CharField(max_length=200, verbose_name='Tên voucher')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm'), ('fixed', 'Số tiền cố định')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị giảm')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giảm tối đa (cho phần trăm)')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lần sử dụng tối đa')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Đã sử dụng')),
                ('valid_from', models.DateTimeField(verbose_name='Có hiệu lực từ')),
                ('valid_to', models.DateTimeField(verbose_name='Có hiệu lực đến')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='shop.product')),
            ],
            options={
                'verbose_name': 'Voucher sản phẩm',
                'verbose_name_plural': 'Voucher sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
